apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
patchesStrategicMerge:
  - podinfo-values.yaml
resources:
  - ../base/podinfo
  - ./s3-bucket.yaml # Include our new bucket
